### PR TITLE
Feature fix build plugins

### LINKED ISSUE #66: ktLint is failing [Old dependencies maybe]
**Describe the bug**
We have a local bash script that runs analysis on the code, which fails

**To Reproduce**
1. On your terminal, run `./codeAnalysis`
2. Check the error thrown on the console/emulator

**Expected behavior**
The task should run and complete successfully

**Screenshots**

### PR DESCRIPTION
**Pull request by jumaallan**
This PR
* Fixes ktLint failure
* Updates detekt rules
* Suppress a few warnings - we're rewriting the lib again
* Formatting codebase

### CODE REVIEW

File: buildSrc/src/main/kotlin/Dependencies.kt [hunk 1]
```diff
@@ -25,9 +25,9 @@ object Versions {
     const val coreKtx = "1.5.0-alpha02"
 
     // Gradle Plugins
-    const val ktlint = "9.3.0"
+    const val ktlint = "10.1.0"
     const val detekt = "1.18.0-RC2"
```
Comment (wangerekaharun) [inline buildSrc/src/main/kotlin/Dependencies.kt]: detekt has a new version, 18.0.0 which has new additions and rules, might be worth an upgrade

**Review by wangerekaharun — CHANGES_REQUESTED** [review]

File: buildSrc/src/main/kotlin/Dependencies.kt (hunk 1 above)
Comment (jumaallan) [reply buildSrc/src/main/kotlin/Dependencies.kt]: The new version is 1.18.0 actually 😄

Comment (wangerekaharun) [reply buildSrc/src/main/kotlin/Dependencies.kt]: Yes😅 missed the one :-(

Comment (jumaallan) [reply buildSrc/src/main/kotlin/Dependencies.kt]: Where do we get the rules from btw? I normally use your template, so I've never really looked at it. The `detekt.yml` file content?

Comment (wangerekaharun) [reply buildSrc/src/main/kotlin/Dependencies.kt]: The file is for enabling/ disabling rules. So for new files, it doesn't automatically pick them or add them unless they're enabled by default on the library. But you can always check the [change log](https://detekt.github.io/detekt/changelog.html#1180---2021-08-12) to see if there's a rule you'll need to add.

Comment (jumaallan) [reply buildSrc/src/main/kotlin/Dependencies.kt]: That's what I wanted to ask, since I saw it print that some rules were deprecated. I will work on this within the day

File: detekt.yml [hunk 2]
```diff
@@ -24,25 +24,6 @@ console-reports:
   #  - 'FindingsReport'
   #  - 'BuildFailureReport'
 
-comments:
```
Comment (jumaallan) [inline detekt.yml:27]: @wangerekaharun I can see the file was auto edited actually :)

So I guess were good to go

Comment (wangerekaharun) [reply detekt.yml:27]: Interesting, never knew that it does so.

Comment (jumaallan) [reply detekt.yml:27]: I didn't edit the files, so I am assuming the plugin does that out of the box. Subject to confirmation though

**Comment by jumaallan** [comment]
I've pulled from master, on this branch, and run formatting too on the codebase 🤖

**Review by wangerekaharun — APPROVED** [review]
